// <auto-generated />
using System;
using AkilliFitApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkilliFitApp.Infrastructure.Migrations
{
    [DbContext(typeof(AkilliFitAppDbContext))]
    partial class AkilliFitAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("EgzersizBilgiSequence");

            modelBuilder.HasSequence("EgzersizSequence");

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.Besin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kalori100gr")
                        .HasColumnType("int");

                    b.Property<double>("Karbonhidrat100gr")
                        .HasColumnType("float");

                    b.Property<double>("Protein100gr")
                        .HasColumnType("float");

                    b.Property<double>("Yag100gr")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Besinler");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.DiyetBesin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BesinId")
                        .HasColumnType("int");

                    b.Property<int>("DiyetProgramId")
                        .HasColumnType("int");

                    b.Property<double>("Gramaj")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BesinId");

                    b.HasIndex("DiyetProgramId");

                    b.ToTable("DiyetBesinleri");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.DiyetProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("DiyetProgramlari");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.Egzersiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [EgzersizSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.EgzersizBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [EgzersizBilgiSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("EgzersizId")
                        .HasColumnType("int");

                    b.Property<int>("EgzersizProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EgzersizId");

                    b.HasIndex("EgzersizProgramId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.EgzersizNot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EgzersizBilgiId")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EgzersizBilgiId")
                        .IsUnique();

                    b.ToTable("EgzersizNotlari");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.EgzersizProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("EgzersizProgramlari");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AktiviteSeviyesi")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<double>("HedefKilo")
                        .HasColumnType("float");

                    b.Property<double>("Kilo")
                        .HasColumnType("float");

                    b.Property<string>("ProfilResmiUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.AgirlikEgzersiz", b =>
                {
                    b.HasBaseType("AkilliFitApp.Domain.Entities.Egzersiz");

                    b.ToTable("AgirlikEgzersiz", (string)null);
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.KardiyoEgzersiz", b =>
                {
                    b.HasBaseType("AkilliFitApp.Domain.Entities.Egzersiz");

                    b.ToTable("KardiyoEgzersiz", (string)null);
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.AgirlikEgzersizBilgi", b =>
                {
                    b.HasBaseType("AkilliFitApp.Domain.Entities.EgzersizBilgi");

                    b.Property<int?>("AgirlikEgzersizId")
                        .HasColumnType("int");

                    b.Property<double>("AgirlikKG")
                        .HasColumnType("float");

                    b.Property<double>("HedeflenenAgirlikKG")
                        .HasColumnType("float");

                    b.Property<int>("Set")
                        .HasColumnType("int");

                    b.Property<int>("Tekrar")
                        .HasColumnType("int");

                    b.HasIndex("AgirlikEgzersizId");

                    b.HasIndex("EgzersizProgramId", "EgzersizId")
                        .IsUnique();

                    b.ToTable("AgirlikEgzersizBilgileri", (string)null);
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.KardiyoEgzersizBilgi", b =>
                {
                    b.HasBaseType("AkilliFitApp.Domain.Entities.EgzersizBilgi");

                    b.Property<double>("HedeflenenMesafe")
                        .HasColumnType("float");

                    b.Property<TimeOnly>("HedeflenenSure")
                        .HasColumnType("time");

                    b.Property<int?>("KardiyoEgzersizId")
                        .HasColumnType("int");

                    b.Property<double>("MesafeMtr")
                        .HasColumnType("float");

                    b.Property<TimeOnly>("Sure")
                        .HasColumnType("time");

                    b.HasIndex("KardiyoEgzersizId");

                    b.HasIndex("EgzersizProgramId", "EgzersizId")
                        .IsUnique();

                    b.ToTable("KardiyoEgzersizBilgileri", (string)null);
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.DiyetBesin", b =>
                {
                    b.HasOne("AkilliFitApp.Domain.Entities.Besin", "Besin")
                        .WithMany("DiyetBesinler")
                        .HasForeignKey("BesinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AkilliFitApp.Domain.Entities.DiyetProgram", "DiyetProgram")
                        .WithMany("DiyetBesinleri")
                        .HasForeignKey("DiyetProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Besin");

                    b.Navigation("DiyetProgram");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.DiyetProgram", b =>
                {
                    b.HasOne("AkilliFitApp.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("DiyetProgramlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.EgzersizBilgi", b =>
                {
                    b.HasOne("AkilliFitApp.Domain.Entities.Egzersiz", "Egzersiz")
                        .WithMany()
                        .HasForeignKey("EgzersizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AkilliFitApp.Domain.Entities.EgzersizProgram", "EgzersizProgram")
                        .WithMany("EgzersizBilgi")
                        .HasForeignKey("EgzersizProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Egzersiz");

                    b.Navigation("EgzersizProgram");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.EgzersizNot", b =>
                {
                    b.HasOne("AkilliFitApp.Domain.Entities.EgzersizBilgi", "EgzersizBilgi")
                        .WithOne("EgzersizNot")
                        .HasForeignKey("AkilliFitApp.Domain.Entities.EgzersizNot", "EgzersizBilgiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EgzersizBilgi");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.EgzersizProgram", b =>
                {
                    b.HasOne("AkilliFitApp.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("EgzersizProgramlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.AgirlikEgzersizBilgi", b =>
                {
                    b.HasOne("AkilliFitApp.Domain.Entities.AgirlikEgzersiz", null)
                        .WithMany("AgirlikEgzersizBilgileri")
                        .HasForeignKey("AgirlikEgzersizId");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.KardiyoEgzersizBilgi", b =>
                {
                    b.HasOne("AkilliFitApp.Domain.Entities.KardiyoEgzersiz", null)
                        .WithMany("KardiyoEgzersizBilgileri")
                        .HasForeignKey("KardiyoEgzersizId");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.Besin", b =>
                {
                    b.Navigation("DiyetBesinler");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.DiyetProgram", b =>
                {
                    b.Navigation("DiyetBesinleri");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.EgzersizBilgi", b =>
                {
                    b.Navigation("EgzersizNot");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.EgzersizProgram", b =>
                {
                    b.Navigation("EgzersizBilgi");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("DiyetProgramlar");

                    b.Navigation("EgzersizProgramlar");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.AgirlikEgzersiz", b =>
                {
                    b.Navigation("AgirlikEgzersizBilgileri");
                });

            modelBuilder.Entity("AkilliFitApp.Domain.Entities.KardiyoEgzersiz", b =>
                {
                    b.Navigation("KardiyoEgzersizBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
